<HomeNav>:
	name: root.name
	icon: root.icon

	MDFloatLayout:
		#orientation: "horizontal"
		#size_hint: 1, 1

		MDRaisedButton:
			text: "APPLY"
			font_size: "16sp"
			padding: ["32dp", "16dp", "32dp", "16dp"]
			#id: applybtn
			on_press: self.parent.parent.set_theme(self)
			#size_hint: 0.05, 0.05
			pos_hint: {"center_x": 0.5, "y": 0.1}

		MDIconButton:
			#pos_hint: {'top': 0}#{'x': 1, 'y': 0}
			icon: 'bug-outline'
			id: debug_btn

